In [4]:
import pandas as pd
import numpy as np

In [2]:
XY = pd.read_parquet('FX_test.parquet')

In [6]:
Y = np.log(XY[['HG=F']])
X = np.log(XY.drop(columns = ['HG=F']))

In [27]:
def ds(Y, X, k):
    Yk = Y.diff(k)
    Xk = X.diff(k).shift(1)
    data = Yk.join(Xk).dropna()
    return data[Y.columns], data[X.columns]

In [28]:
def expanding_outer_split(
    X,
    Y,
    outer_train=2000,
    outer_test=60,
    step=60,
    h=1,
):
    embargo = h - 1
    n = len(X)
    split_num = 0
    test_start = outer_train

    while test_start + outer_test <= n:
        train_end = test_start - embargo

        if train_end <= 0:
            break
        yield {
            "split": split_num,
            "X_train": X.iloc[:train_end],
            "Y_train": Y.iloc[:train_end],
            "X_test": X.iloc[test_start:test_start + outer_test],
            "Y_test": Y.iloc[test_start:test_start + outer_test],
        }
        split_num += 1
        test_start += step

In [29]:
Y1, X1 = ds(Y, X, 1)
Y5, X5 = ds(Y, X, 5)
Y20, X20 = ds(Y, X, 20)

splits1 = list(expanding_outer_split(X1, Y1, outer_train=2000, outer_test=60, step=60, h=1))
splits5 = list(expanding_outer_split(X5, Y5, outer_train=2000, outer_test=60, step=60, h=5))
splits20 = list(expanding_outer_split(X20, Y20, outer_train=2000, outer_test=60, step=60, h=20))

In [32]:
def ic(y, yhat):
    y = pd.Series(np.asarray(y).ravel())
    yhat = pd.Series(np.asarray(yhat).ravel())
    return y.corr(yhat, method="spearman")

def rmse(y, yhat):
    y = np.asarray(y).ravel()
    yhat = np.asarray(yhat).ravel()
    return np.sqrt(np.mean((y - yhat)**2))

def r2(y, yhat):
    y = np.asarray(y).ravel()
    yhat = np.asarray(yhat).ravel()
    ss_res = np.sum((y - yhat)**2)
    ss_tot = np.sum((y - y.mean())**2)
    return np.nan if ss_tot == 0 else 1 - ss_res / ss_tot

def tstat(x):
    x = np.asarray(x, dtype=float)
    x = x[~np.isnan(x)]
    return np.nan if len(x) < 2 else x.mean() / (x.std(ddof=1) / np.sqrt(len(x)))

In [40]:
def oos_metrics(y_true_folds, y_pred_folds, return_folds=False):
    ic_list   = [ic(y, yhat)   for y, yhat in zip(y_true_folds, y_pred_folds)]
    rmse_list = [rmse(y, yhat) for y, yhat in zip(y_true_folds, y_pred_folds)]
    r2_list   = [r2(y, yhat)   for y, yhat in zip(y_true_folds, y_pred_folds)]

    res = {
        "mean_oos_ic": np.nanmean(ic_list),
        "tstat_ic": tstat(ic_list),
        "mean_oos_rmse": np.nanmean(rmse_list),
        "mean_oos_r2": np.nanmean(r2_list),
    }

    if return_folds:
        res.update({
            "ic_folds": ic_list,
            "rmse_folds": rmse_list,
            "r2_folds": r2_list,
        })

    return res

Mean Forecast (0)

In [34]:
def zero_baseline(splits):
    y_true_folds = []
    y_pred_folds = []

    for fold in splits:
        y = fold["Y_test"].values.ravel()
        yhat = np.zeros_like(y)
        y_true_folds.append(y)
        y_pred_folds.append(yhat)

    return oos_metrics(y_true_folds, y_pred_folds)

In [35]:
res1 = zero_baseline(splits1)
res5 = zero_baseline(splits5)
res20 = zero_baseline(splits20)

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/var/folders/43/y646xgv56z72xq7sm281s4zr0000gn/T/ipykernel_23342/3454508213.py:7: RuntimeWarning: Mean of empty slice
  "mean_oos_ic": np.nanmean(ic_list),

In [41]:
res1 = zero_baseline(splits1)
res5 = zero_baseline(splits5)
res20 = zero_baseline(splits20)

results = pd.DataFrame({
    "h=1": res1,
    "h=5": res5,
    "h=20": res20,
}).T

display(results.round(6))

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/pandas/core/nanops.py:1632: ConstantInputWarning: An input array is constant; the correlation coefficient is not defined.
  return spearmanr(a, b)[0]
/var/folders/43/y646xgv56z72xq7sm281s4zr0000gn/T/ipykernel_23342/3052757927.py:7: RuntimeWarning: Mean of empty slice
  "mean_oos_ic": np.nanmean(ic_list),

      mean_oos_ic  tstat_ic  mean_oos_rmse  mean_oos_r2
h=1           NaN       NaN       0.014553    -0.014521
h=5           NaN       NaN       0.031467    -0.096768
h=20          NaN       NaN       0.058803    -0.614936

ridge

In [44]:
import optuna
from sklearn.linear_model import Ridge
from sklearn.preprocessing import StandardScaler
def ridge_oos(splits, val_size=252, n_trials=30, seed=42):
    y_true_folds = []
    y_pred_folds = []

    for fold in splits:
        X_train = fold["X_train"]
        Y_train = fold["Y_train"].values.ravel()
        X_test  = fold["X_test"]
        Y_test  = fold["Y_test"].values.ravel()

        X_tr = X_train.iloc[:-val_size]
        y_tr = Y_train[:-val_size]
        X_val = X_train.iloc[-val_size:]
        y_val = Y_train[-val_size:]

        def objective(trial):
            alpha = trial.suggest_float("alpha", 1e-4, 1e4, log=True)

            scaler = StandardScaler()
            X_tr_s = scaler.fit_transform(X_tr)
            X_val_s = scaler.transform(X_val)

            model = Ridge(alpha=alpha)
            model.fit(X_tr_s, y_tr)
            y_val_pred = model.predict(X_val_s)

            return rmse(y_val, y_val_pred)

        study = optuna.create_study(direction="minimize",
                                    sampler=optuna.samplers.TPESampler(seed=seed))
        study.optimize(objective, n_trials=n_trials, show_progress_bar=False)

        best_alpha = study.best_params["alpha"]

        scaler = StandardScaler()
        X_train_s = scaler.fit_transform(X_train)
        X_test_s = scaler.transform(X_test)

        model = Ridge(alpha=best_alpha)
        model.fit(X_train_s, Y_train)
        y_pred = model.predict(X_test_s)

        y_true_folds.append(Y_test)
        y_pred_folds.append(y_pred)

    return oos_metrics(y_true_folds, y_pred_folds)

In [45]:
res_ridge_1 = ridge_oos(splits1, val_size=252, n_trials=30)
res_ridge_5 = ridge_oos(splits5, val_size=252, n_trials=30)
res_ridge_20 = ridge_oos(splits20, val_size=252, n_trials=30)

[I 2026-04-19 14:57:19,616] A new study created in memory with name: no-name-213b3888-6e9b-43b5-b368-654e66508bf8
[I 2026-04-19 14:57:19,655] Trial 0 finished with value: 0.015178527717396601 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.015178527717396601.
[I 2026-04-19 14:57:19,660] Trial 1 finished with value: 0.014338403783346804 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,664] Trial 2 finished with value: 0.015149223085372214 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,667] Trial 3 finished with value: 0.015194166555354634 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,670] Trial 4 finished with value: 0.015178870440677276 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,673] Trial 5 finished with value: 0.015178870443720474 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,677] Trial 6 finished with value: 0.015178876171436973 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,679] Trial 7 finished with value: 0.014643658732155694 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,682] Trial 8 finished with value: 0.015194963744959896 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,684] Trial 9 finished with value: 0.01518436175148893 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.014338403783346804.
[I 2026-04-19 14:57:19,691] Trial 10 finished with value: 0.014285522900912851 and parameters: {'alpha': 6854.231317270694}. Best is trial 10 with value: 0.014285522900912851.
[I 2026-04-19 14:57:19,695] Trial 11 finished with value: 0.014384365135457433 and parameters: {'alpha': 2903.3273118298125}. Best is trial 10 with value: 0.014285522900912851.
[I 2026-04-19 14:57:19,699] Trial 12 finished with value: 0.014301098111515252 and parameters: {'alpha': 5705.54173238389}. Best is trial 10 with value: 0.014285522900912851.
[I 2026-04-19 14:57:19,702] Trial 13 finished with value: 0.014926604304432003 and parameters: {'alpha': 272.72982185916777}. Best is trial 10 with value: 0.014285522900912851.
[I 2026-04-19 14:57:19,706] Trial 14 finished with value: 0.014270699052074462 and parameters: {'alpha': 8467.975927999696}. Best is trial 14 with value: 0.014270699052074462.
[I 2026-04-19 14:57:19,710] Trial 15 finished with value: 0.01517866995080641 and parameters: {'alpha': 0.05635602497291169}. Best is trial 14 with value: 0.014270699052074462.
[I 2026-04-19 14:57:19,713] Trial 16 finished with value: 0.014879576671484233 and parameters: {'alpha': 333.65932463125364}. Best is trial 14 with value: 0.014270699052074462.
[I 2026-04-19 14:57:19,717] Trial 17 finished with value: 0.015180698330596746 and parameters: {'alpha': 2.1003179206161295}. Best is trial 14 with value: 0.014270699052074462.
[I 2026-04-19 14:57:19,720] Trial 18 finished with value: 0.015147757716950185 and parameters: {'alpha': 72.81630248279436}. Best is trial 14 with value: 0.014270699052074462.
[I 2026-04-19 14:57:19,724] Trial 19 finished with value: 0.014263372113009156 and parameters: {'alpha': 9590.683921983196}. Best is trial 19 with value: 0.014263372113009156.
[I 2026-04-19 14:57:19,728] Trial 20 finished with value: 0.015177942322542885 and parameters: {'alpha': 0.3530343009318503}. Best is trial 19 with value: 0.014263372113009156.
[I 2026-04-19 14:57:19,732] Trial 21 finished with value: 0.014291122481335895 and parameters: {'alpha': 6393.140913511499}. Best is trial 19 with value: 0.014263372113009156.
[I 2026-04-19 14:57:19,735] Trial 22 finished with value: 0.014647572025540862 and parameters: {'alpha': 836.8671967096351}. Best is trial 19 with value: 0.014263372113009156.
[I 2026-04-19 14:57:19,739] Trial 23 finished with value: 0.014269580840917163 and parameters: {'alpha': 8621.496643688846}. Best is trial 19 with value: 0.014263372113009156.
[I 2026-04-19 14:57:19,744] Trial 24 finished with value: 0.014550307748616742 and parameters: {'alpha': 1248.311507322139}. Best is trial 19 with value: 0.014263372113009156.
[I 2026-04-19 14:57:19,747] Trial 25 finished with value: 0.01499896687130893 and parameters: {'alpha': 194.3560960129936}. Best is trial 19 with value: 0.014263372113009156.
[I 2026-04-19 14:57:19,751] Trial 26 finished with value: 0.015207516992724003 and parameters: {'alpha': 14.528624920816956}. Best is trial 19 with value: 0.014263372113009156.
[I 2026-04-19 14:57:19,754] Trial 27 finished with value: 0.01426189680950628 and parameters: {'alpha': 9855.415049127516}. Best is trial 27 with value: 0.01426189680950628.
[I 2026-04-19 14:57:19,758] Trial 28 finished with value: 0.014529112347483464 and parameters: {'alpha': 1369.4130987707636}. Best is trial 27 with value: 0.01426189680950628.
[I 2026-04-19 14:57:19,762] Trial 29 finished with value: 0.015178444845763046 and parameters: {'alpha': 0.12611119254047898}. Best is trial 27 with value: 0.01426189680950628.
[I 2026-04-19 14:57:19,765] A new study created in memory with name: no-name-37c424fd-9f4f-461e-ab40-4c257013e2be
[I 2026-04-19 14:57:19,768] Trial 0 finished with value: 0.015129223951720963 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.015129223951720963.
[I 2026-04-19 14:57:19,770] Trial 1 finished with value: 0.014508487426372141 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,772] Trial 2 finished with value: 0.016750950999922767 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,775] Trial 3 finished with value: 0.015410772256060006 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,777] Trial 4 finished with value: 0.015135057200332518 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,779] Trial 5 finished with value: 0.01513505725253929 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,781] Trial 6 finished with value: 0.015135155528335872 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,784] Trial 7 finished with value: 0.016073766449362037 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,786] Trial 8 finished with value: 0.015429241336254446 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,789] Trial 9 finished with value: 0.016570041938968636 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.014508487426372141.
[I 2026-04-19 14:57:19,793] Trial 10 finished with value: 0.014323026991483688 and parameters: {'alpha': 6854.231317270694}. Best is trial 10 with value: 0.014323026991483688.
[I 2026-04-19 14:57:19,796] Trial 11 finished with value: 0.014735945434544182 and parameters: {'alpha': 2903.3273118298125}. Best is trial 10 with value: 0.014323026991483688.
[I 2026-04-19 14:57:19,800] Trial 12 finished with value: 0.01436510273265724 and parameters: {'alpha': 5705.54173238389}. Best is trial 10 with value: 0.014323026991483688.
[I 2026-04-19 14:57:19,803] Trial 13 finished with value: 0.016817806984582795 and parameters: {'alpha': 272.72982185916777}. Best is trial 10 with value: 0.014323026991483688.
[I 2026-04-19 14:57:19,808] Trial 14 finished with value: 0.014296388042694227 and parameters: {'alpha': 8467.975927999696}. Best is trial 14 with value: 0.014296388042694227.
[I 2026-04-19 14:57:19,812] Trial 15 finished with value: 0.015131634977754008 and parameters: {'alpha': 0.05635602497291169}. Best is trial 14 with value: 0.014296388042694227.
[I 2026-04-19 14:57:19,815] Trial 16 finished with value: 0.016750345992554032 and parameters: {'alpha': 333.65932463125364}. Best is trial 14 with value: 0.014296388042694227.
[I 2026-04-19 14:57:19,818] Trial 17 finished with value: 0.015157563587329306 and parameters: {'alpha': 2.1003179206161295}. Best is trial 14 with value: 0.014296388042694227.
[I 2026-04-19 14:57:19,822] Trial 18 finished with value: 0.016755681258708906 and parameters: {'alpha': 72.81630248279436}. Best is trial 14 with value: 0.014296388042694227.
[I 2026-04-19 14:57:19,827] Trial 19 finished with value: 0.014289032106968589 and parameters: {'alpha': 9590.683921983196}. Best is trial 19 with value: 0.014289032106968589.
[I 2026-04-19 14:57:19,830] Trial 20 finished with value: 0.015119285380917174 and parameters: {'alpha': 0.3530343009318503}. Best is trial 19 with value: 0.014289032106968589.
[I 2026-04-19 14:57:19,834] Trial 21 finished with value: 0.014336653720761003 and parameters: {'alpha': 6393.140913511499}. Best is trial 19 with value: 0.014289032106968589.
[I 2026-04-19 14:57:19,838] Trial 22 finished with value: 0.016089850914141897 and parameters: {'alpha': 836.8671967096351}. Best is trial 19 with value: 0.014289032106968589.
[I 2026-04-19 14:57:19,842] Trial 23 finished with value: 0.014294996311944091 and parameters: {'alpha': 8621.496643688846}. Best is trial 19 with value: 0.014289032106968589.
[I 2026-04-19 14:57:19,845] Trial 24 finished with value: 0.01564269661860145 and parameters: {'alpha': 1248.311507322139}. Best is trial 19 with value: 0.014289032106968589.
[I 2026-04-19 14:57:19,849] Trial 25 finished with value: 0.016878692761592005 and parameters: {'alpha': 194.3560960129936}. Best is trial 19 with value: 0.014289032106968589.
[I 2026-04-19 14:57:19,853] Trial 26 finished with value: 0.015868585898726396 and parameters: {'alpha': 14.528624920816956}. Best is trial 19 with value: 0.014289032106968589.
[I 2026-04-19 14:57:19,857] Trial 27 finished with value: 0.014288075402982178 and parameters: {'alpha': 9855.415049127516}. Best is trial 27 with value: 0.014288075402982178.
[I 2026-04-19 14:57:19,861] Trial 28 finished with value: 0.015533281000748562 and parameters: {'alpha': 1369.4130987707636}. Best is trial 27 with value: 0.014288075402982178.
[I 2026-04-19 14:57:19,865] Trial 29 finished with value: 0.015127823417337656 and parameters: {'alpha': 0.12611119254047898}. Best is trial 27 with value: 0.014288075402982178.
[I 2026-04-19 14:57:19,868] A new study created in memory with name: no-name-f58218a0-d368-47af-b5dc-2710eedc1862
[I 2026-04-19 14:57:19,870] Trial 0 finished with value: 0.014851029113017692 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.014851029113017692.
[I 2026-04-19 14:57:19,873] Trial 1 finished with value: 0.01420281672610986 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,875] Trial 2 finished with value: 0.014646352801025844 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,878] Trial 3 finished with value: 0.01461677579132907 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,880] Trial 4 finished with value: 0.014851211292291316 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,882] Trial 5 finished with value: 0.01485121129127149 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,885] Trial 6 finished with value: 0.01485120930247703 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,887] Trial 7 finished with value: 0.01463078449198365 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,890] Trial 8 finished with value: 0.014609565133220107 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,892] Trial 9 finished with value: 0.014595156965120823 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.01420281672610986.
[I 2026-04-19 14:57:19,896] Trial 10 finished with value: 0.014168195413747987 and parameters: {'alpha': 6854.231317270694}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,899] Trial 11 finished with value: 0.014263583702235709 and parameters: {'alpha': 2903.3273118298125}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,903] Trial 12 finished with value: 0.014172599978635628 and parameters: {'alpha': 5705.54173238389}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,907] Trial 13 finished with value: 0.014746346135902312 and parameters: {'alpha': 272.72982185916777}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,911] Trial 14 finished with value: 0.01417006603949795 and parameters: {'alpha': 8467.975927999696}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,914] Trial 15 finished with value: 0.014851184468098796 and parameters: {'alpha': 0.05635602497291169}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,918] Trial 16 finished with value: 0.014746165616394639 and parameters: {'alpha': 333.65932463125364}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,921] Trial 17 finished with value: 0.014775134710072194 and parameters: {'alpha': 2.1003179206161295}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,925] Trial 18 finished with value: 0.014647986221374846 and parameters: {'alpha': 72.81630248279436}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,928] Trial 19 finished with value: 0.014173543206579152 and parameters: {'alpha': 9590.683921983196}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,931] Trial 20 finished with value: 0.014848418510442881 and parameters: {'alpha': 0.3239359537496942}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,935] Trial 21 finished with value: 0.014507865630709806 and parameters: {'alpha': 1301.0747883515403}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,939] Trial 22 finished with value: 0.014168202034159976 and parameters: {'alpha': 6847.579101511254}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,943] Trial 23 finished with value: 0.014652099107663906 and parameters: {'alpha': 775.3570689234512}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,947] Trial 24 finished with value: 0.014173337700780792 and parameters: {'alpha': 9530.74189642418}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,950] Trial 25 finished with value: 0.014734432792446352 and parameters: {'alpha': 194.3560960129936}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,954] Trial 26 finished with value: 0.014554729600026496 and parameters: {'alpha': 31.6118048866516}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,958] Trial 27 finished with value: 0.014379650508311186 and parameters: {'alpha': 1923.1799831414148}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,962] Trial 28 finished with value: 0.014526309676832232 and parameters: {'alpha': 13.935589824448938}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,966] Trial 29 finished with value: 0.01485122328923288 and parameters: {'alpha': 0.026333428460614747}. Best is trial 10 with value: 0.014168195413747987.
[I 2026-04-19 14:57:19,968] A new study created in memory with name: no-name-2e918375-89f9-4e76-b5cc-5201e51c5cee
[I 2026-04-19 14:57:19,970] Trial 0 finished with value: 0.015853994690185703 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.015853994690185703.
[I 2026-04-19 14:57:19,973] Trial 1 finished with value: 0.01426685312987143 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,975] Trial 2 finished with value: 0.01459273370328365 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,978] Trial 3 finished with value: 0.015398122610023582 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,980] Trial 4 finished with value: 0.01585224142285186 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,982] Trial 5 finished with value: 0.01585224140401841 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,984] Trial 6 finished with value: 0.015852205871446118 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,986] Trial 7 finished with value: 0.014389609523000849 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,989] Trial 8 finished with value: 0.015378479470354468 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,991] Trial 9 finished with value: 0.014665917901194139 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,995] Trial 10 finished with value: 0.014268728576127477 and parameters: {'alpha': 6854.231317270694}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:19,999] Trial 11 finished with value: 0.014282225555655633 and parameters: {'alpha': 2903.3273118298125}. Best is trial 1 with value: 0.01426685312987143.
[I 2026-04-19 14:57:20,002] Trial 12 finished with value: 0.014264948432524068 and parameters: {'alpha': 5705.54173238389}. Best is trial 12 with value: 0.014264948432524068.
[I 2026-04-19 14:57:20,006] Trial 13 finished with value: 0.014446138946089784 and parameters: {'alpha': 325.98171890867656}. Best is trial 12 with value: 0.014264948432524068.
[I 2026-04-19 14:57:20,010] Trial 14 finished with value: 0.015854497379398313 and parameters: {'alpha': 0.15678038290530655}. Best is trial 12 with value: 0.014264948432524068.
[I 2026-04-19 14:57:20,014] Trial 15 finished with value: 0.014461023092114979 and parameters: {'alpha': 261.57663310789206}. Best is trial 12 with value: 0.014264948432524068.
[I 2026-04-19 14:57:20,017] Trial 16 finished with value: 0.014273059801750542 and parameters: {'alpha': 7885.275730239739}. Best is trial 12 with value: 0.014264948432524068.
[I 2026-04-19 14:57:20,021] Trial 17 finished with value: 0.015187429436705332 and parameters: {'alpha': 9.832596499596548}. Best is trial 12 with value: 0.014264948432524068.
[I 2026-04-19 14:57:20,025] Trial 18 finished with value: 0.015832180316733425 and parameters: {'alpha': 0.9060546871526479}. Best is trial 12 with value: 0.014264948432524068.
[I 2026-04-19 14:57:20,029] Trial 19 finished with value: 0.014429894946880253 and parameters: {'alpha': 428.1575215324218}. Best is trial 12 with value: 0.014264948432524068.
[I 2026-04-19 14:57:20,032] Trial 20 finished with value: 0.014353216846281552 and parameters: {'alpha': 1324.670788131889}. Best is trial 12 with value: 0.014264948432524068.

In [46]:
results_ridge = pd.DataFrame({
    "h=1": res_ridge_1,
    "h=5": res_ridge_5,
    "h=20": res_ridge_20,
}).T

display(results_ridge.round(6))

      mean_oos_ic   tstat_ic  mean_oos_rmse  mean_oos_r2
h=1      0.025696   1.346186       0.014576    -0.018322
h=5      0.308879  11.031029       0.030568    -0.090637
h=20     0.421551   7.587647       0.050423    -0.208463

PCA

In [92]:
from sklearn.decomposition import PCA


def pca_oos_table(splits, n_components_list):
    rows = []

    for n_components in n_components_list:
        ev_folds = []

        for fold in splits:
            X_train = fold["X_train"]
            X_test  = fold["X_test"]

            scaler = StandardScaler()
            X_train_s = scaler.fit_transform(X_train)
            X_test_s  = scaler.transform(X_test)

            pca = PCA(n_components=n_components)
            pca.fit(X_train_s)

            Z_test = pca.transform(X_test_s)
            X_test_hat = Z_test @ pca.components_

            ss_total = np.sum(X_test_s ** 2)
            ss_resid = np.sum((X_test_s - X_test_hat) ** 2)

            ev_folds.append(1 - ss_resid / ss_total)

        rows.append({
            "n_components": n_components,
            "mean_oos_explained_variance": np.mean(ev_folds),
        })

    return pd.DataFrame(rows)

In [93]:
tab1 = pca_oos_table(splits1,  [1, 2, 3, 5, 10, 20])
tab5 = pca_oos_table(splits5,  [1, 2, 3, 5, 10, 20])
tab20 = pca_oos_table(splits20, [1, 2, 3, 5, 10, 20])

In [94]:
display(tab1.round(4))
display(tab5.round(4))
display(tab20.round(4))

   n_components  mean_oos_explained_variance
0             1                       0.2486
1             2                       0.3671
2             3                       0.4571
3             5                       0.5608
4            10                       0.7067
5            20                       0.9963

   n_components  mean_oos_explained_variance
0             1                       0.2856
1             2                       0.4369
2             3                       0.5042
3             5                       0.6039
4            10                       0.7352
5            20                       0.9992

   n_components  mean_oos_explained_variance
0             1                       0.2804
1             2                       0.4468
2             3                       0.5130
3             5                       0.6220
4            10                       0.7577
5            20                       0.9998

In [96]:
k = 10
def compute_pca_summary(splits, n_components=k):
    all_loadings = []
    explained_variance = []

    for fold in splits:
        X_train = fold["X_train"]

        scaler = StandardScaler()
        X_train_s = scaler.fit_transform(X_train)

        pca = PCA(n_components=n_components)
        pca.fit(X_train_s)

        loadings = pd.DataFrame(pca.components_.T,
                                index=X_train.columns,
                                columns=[f'PC{i+1}' for i in range(n_components)])
        all_loadings.append(loadings)
        explained_variance.append(pca.explained_variance_ratio_)

    avg_loadings = sum(all_loadings) / len(all_loadings)
    avg_explained_variance = np.mean(explained_variance, axis=0)

    return avg_loadings, avg_explained_variance

def print_top_loadings(loadings, ev, horizon_name):
    print(f"\nHorizon: {horizon_name}")
    print("Explained variance ratio per component:")
    for i, ev_ratio in enumerate(ev):
        print(f"  PC{i+1}: {ev_ratio:.3f}")

    print("\nTop 5 variables per component:")
    for pc in loadings.columns:
        top_vars = loadings[pc].abs().sort_values(ascending=False).head(5)
        print(f"{pc}: {', '.join(top_vars.index)}")
loadings1, ev1 = compute_pca_summary(splits1)
loadings5, ev5 = compute_pca_summary(splits5)
loadings20, ev20 = compute_pca_summary(splits20)

print_top_loadings(loadings1, ev1, "1-step")
print_top_loadings(loadings5, ev5, "5-step")
print_top_loadings(loadings20, ev20, "20-step")

Horizon: 1-step
Explained variance ratio per component:
  PC1: 0.293
  PC2: 0.112
  PC3: 0.072
  PC4: 0.055
  PC5: 0.050
  PC6: 0.040
  PC7: 0.039
  PC8: 0.035
  PC9: 0.035
  PC10: 0.034

Top 5 variables per component:
PC1: AUDUSD=X, AUDJPY=X, NZDJPY=X, NZDUSD=X, EURJPY=X
PC2: USDCHF=X, CADCHF=X, EURCHF=X, USDJPY=X, CADJPY=X
PC3: CHFJPY=X, USDJPY=X, EURCHF=X, EURJPY=X, CADCHF=X
PC4: AUDCAD=X, AUDNZD=X, EURGBP=X, EURUSD=X, EURCHF=X
PC5: EURGBP=X, AUDNZD=X, AUDCAD=X, GBPUSD=X, EURCHF=X
PC6: AUDNZD=X, NZDUSD=X, AUDCAD=X, NZDJPY=X, DX-Y.NYB
PC7: AUDNZD=X, DX-Y.NYB, NZDUSD=X, NZDJPY=X, AUDCAD=X
PC8: USDPEN=X, USDCOP=X, USDCNY=X, USDRUB=X, USDBRL=X
PC9: USDRUB=X, USDPEN=X, USDCLP=X, USDCNY=X, USDCOP=X
PC10: USDCOP=X, USDCLP=X, USDRUB=X, EURUSD=X, USDCNY=X

Horizon: 5-step
Explained variance ratio per component:
  PC1: 0.329
  PC2: 0.129
  PC3: 0.078
  PC4: 0.054
  PC5: 0.050
  PC6: 0.042
  PC7: 0.040
  PC8: 0.035
  PC9: 0.034
  PC10: 0.034

Top 5 variables per component:
PC1: AUDUSD=X, NZDUSD=X, AUDJPY=X, NZDJPY=X, USDCAD=X
PC2: CADCHF=X, USDJPY=X, USDCHF=X, CADJPY=X, AUDJPY=X
PC3: CHFJPY=X, EURCHF=X, CADCHF=X, USDJPY=X, USDCHF=X
PC4: EURGBP=X, EURCHF=X, GBPUSD=X, EURUSD=X, EURJPY=X
PC5: EURGBP=X, AUDCAD=X, AUDNZD=X, GBPUSD=X, EURCHF=X
PC6: AUDNZD=X, NZDUSD=X, NZDJPY=X, AUDCAD=X, USDCAD=X
PC7: GBPUSD=X, EURGBP=X, AUDCAD=X, USDINR=X, EURCHF=X
PC8: USDCOP=X, USDPEN=X, USDCLP=X, USDRUB=X, AUDCAD=X
PC9: USDCLP=X, USDCOP=X, USDRUB=X, USDPEN=X, USDBRL=X
PC10: USDRUB=X, USDCOP=X, USDCLP=X, USDPEN=X, USDCNY=X

Horizon: 20-step
Explained variance ratio per component:
  PC1: 0.356
  PC2: 0.134
  PC3: 0.077
  PC4: 0.058
  PC5: 0.053
  PC6: 0.044
  PC7: 0.036
  PC8: 0.034
  PC9: 0.033
  PC10: 0.033

Top 5 variables per component:
PC1: AUDUSD=X, NZDUSD=X, USDSGD=X, USDNOK=X, USDCAD=X
PC2: USDJPY=X, CADJPY=X, CADCHF=X, USDCHF=X, AUDJPY=X
PC3: CHFJPY=X, CADCHF=X, EURCHF=X, USDCHF=X, USDJPY=X
PC4: EURCHF=X, EURUSD=X, EURJPY=X, EURGBP=X, DX-Y.NYB
PC5: EURGBP=X, GBPUSD=X, AUDNZD=X, AUDCAD=X, USDCNY=X
PC6: AUDNZD=X, NZDUSD=X, NZDJPY=X, GBPUSD=X, EURGBP=X
PC7: AUDCAD=X, USDCLP=X, EURGBP=X, GBPUSD=X, USDCAD=X
PC8: USDCOP=X, USDRUB=X, USDCLP=X, EURGBP=X, USDINR=X
PC9: USDCLP=X, USDCOP=X, AUDCAD=X, GBPUSD=X, EURGBP=X
PC10: USDRUB=X, USDCLP=X, USDPEN=X, USDCAD=X, AUDCAD=X

In [56]:
def pca_ridge_oos(splits, n_components=10, val_size=252, n_trials=30, seed=42):
    y_true_folds = []
    y_pred_folds = []
    ev_folds = []

    for fold in splits:
        X_train = fold["X_train"]
        Y_train = fold["Y_train"].values.ravel()
        X_test  = fold["X_test"]
        Y_test  = fold["Y_test"].values.ravel()

        X_tr  = X_train.iloc[:-val_size]
        y_tr  = Y_train[:-val_size]
        X_val = X_train.iloc[-val_size:]
        y_val = Y_train[-val_size:]

        def objective(trial):
            alpha = trial.suggest_float("alpha", 1e-4, 1e4, log=True)

            scaler = StandardScaler()
            X_tr_s  = scaler.fit_transform(X_tr)
            X_val_s = scaler.transform(X_val)

            pca = PCA(n_components=n_components)
            Z_tr  = pca.fit_transform(X_tr_s)
            Z_val = pca.transform(X_val_s)

            model = Ridge(alpha=alpha)
            model.fit(Z_tr, y_tr)
            y_val_pred = model.predict(Z_val)

            return rmse(y_val, y_val_pred)

        study = optuna.create_study(
            direction="minimize",
            sampler=optuna.samplers.TPESampler(seed=seed)
        )
        study.optimize(objective, n_trials=n_trials, show_progress_bar=False)

        best_alpha = study.best_params["alpha"]

        scaler = StandardScaler()
        X_train_s = scaler.fit_transform(X_train)
        X_test_s  = scaler.transform(X_test)

        pca = PCA(n_components=n_components)
        Z_train = pca.fit_transform(X_train_s)
        Z_test  = pca.transform(X_test_s)

        model = Ridge(alpha=best_alpha)
        model.fit(Z_train, Y_train)
        y_pred = model.predict(Z_test)

        X_test_hat = Z_test @ pca.components_
        ss_total = np.sum(X_test_s ** 2)
        ss_resid = np.sum((X_test_s - X_test_hat) ** 2)
        ev_folds.append(1 - ss_resid / ss_total)

        y_true_folds.append(Y_test)
        y_pred_folds.append(y_pred)

    res = oos_metrics(y_true_folds, y_pred_folds)
    res["mean_oos_pca_explained_variance"] = np.mean(ev_folds)
    res["pca_explained_variance_folds"] = ev_folds
    return res

In [57]:
res_pca_ridge_1  = pca_ridge_oos(splits1,  n_components=10, val_size=252, n_trials=30)
res_pca_ridge_5  = pca_ridge_oos(splits5,  n_components=10, val_size=252, n_trials=30)
res_pca_ridge_20 = pca_ridge_oos(splits20, n_components=10, val_size=252, n_trials=30)

[I 2026-04-19 15:10:02,188] A new study created in memory with name: no-name-f222811d-3774-4cbc-94a8-e9e0865ebccc
[I 2026-04-19 15:10:02,240] Trial 0 finished with value: 0.014503624265445084 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.014503624265445084.
[I 2026-04-19 15:10:02,243] Trial 1 finished with value: 0.014276982431990609 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,246] Trial 2 finished with value: 0.014489985117168577 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,249] Trial 3 finished with value: 0.014502425998595284 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,252] Trial 4 finished with value: 0.014503643605233466 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,255] Trial 5 finished with value: 0.01450364360538968 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,257] Trial 6 finished with value: 0.014503643899004052 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,260] Trial 7 finished with value: 0.014392631869012518 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,262] Trial 8 finished with value: 0.014502369838278083 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,266] Trial 9 finished with value: 0.014494720010608527 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.014276982431990609.
[I 2026-04-19 15:10:02,272] Trial 10 finished with value: 0.014250162629673872 and parameters: {'alpha': 6854.231317270694}. Best is trial 10 with value: 0.014250162629673872.
[I 2026-04-19 15:10:02,275] Trial 11 finished with value: 0.014298478892048733 and parameters: {'alpha': 2903.3273118298125}. Best is trial 10 with value: 0.014250162629673872.
[I 2026-04-19 15:10:02,279] Trial 12 finished with value: 0.014258281399620442 and parameters: {'alpha': 5705.54173238389}. Best is trial 10 with value: 0.014250162629673872.
[I 2026-04-19 15:10:02,284] Trial 13 finished with value: 0.01445718930550259 and parameters: {'alpha': 272.72982185916777}. Best is trial 10 with value: 0.014250162629673872.
[I 2026-04-19 15:10:02,288] Trial 14 finished with value: 0.014242307756976833 and parameters: {'alpha': 8467.975927999696}. Best is trial 14 with value: 0.014242307756976833.
[I 2026-04-19 15:10:02,292] Trial 15 finished with value: 0.014503632764880137 and parameters: {'alpha': 0.05635602497291169}. Best is trial 14 with value: 0.014242307756976833.
[I 2026-04-19 15:10:02,296] Trial 16 finished with value: 0.01444856942044124 and parameters: {'alpha': 333.65932463125364}. Best is trial 14 with value: 0.014242307756976833.
[I 2026-04-19 15:10:02,301] Trial 17 finished with value: 0.014503227360848277 and parameters: {'alpha': 2.1003179206161295}. Best is trial 14 with value: 0.014242307756976833.
[I 2026-04-19 15:10:02,305] Trial 18 finished with value: 0.014489794690487922 and parameters: {'alpha': 72.81630248279436}. Best is trial 14 with value: 0.014242307756976833.
[I 2026-04-19 15:10:02,308] Trial 19 finished with value: 0.014238402217544611 and parameters: {'alpha': 9590.683921983196}. Best is trial 19 with value: 0.014238402217544611.
[I 2026-04-19 15:10:02,312] Trial 20 finished with value: 0.014503573858693669 and parameters: {'alpha': 0.3530343009318503}. Best is trial 19 with value: 0.014238402217544611.
[I 2026-04-19 15:10:02,317] Trial 21 finished with value: 0.014253100036420312 and parameters: {'alpha': 6393.140913511499}. Best is trial 19 with value: 0.014238402217544611.
[I 2026-04-19 15:10:02,321] Trial 22 finished with value: 0.014393759010219071 and parameters: {'alpha': 836.8671967096351}. Best is trial 19 with value: 0.014238402217544611.
[I 2026-04-19 15:10:02,325] Trial 23 finished with value: 0.014241712054915529 and parameters: {'alpha': 8621.496643688846}. Best is trial 19 with value: 0.014238402217544611.
[I 2026-04-19 15:10:02,329] Trial 24 finished with value: 0.014363395776923013 and parameters: {'alpha': 1248.311507322139}. Best is trial 19 with value: 0.014238402217544611.
[I 2026-04-19 15:10:02,334] Trial 25 finished with value: 0.014469123486934295 and parameters: {'alpha': 194.3560960129936}. Best is trial 19 with value: 0.014238402217544611.
[I 2026-04-19 15:10:02,338] Trial 26 finished with value: 0.01450078375410578 and parameters: {'alpha': 14.528624920816956}. Best is trial 19 with value: 0.014238402217544611.
[I 2026-04-19 15:10:02,342] Trial 27 finished with value: 0.01423761602084042 and parameters: {'alpha': 9855.415049127516}. Best is trial 27 with value: 0.01423761602084042.
[I 2026-04-19 15:10:02,346] Trial 28 finished with value: 0.01435608862822888 and parameters: {'alpha': 1369.4130987707636}. Best is trial 27 with value: 0.01423761602084042.
[I 2026-04-19 15:10:02,351] Trial 29 finished with value: 0.01450361891291758 and parameters: {'alpha': 0.12611119254047898}. Best is trial 27 with value: 0.01423761602084042.
[I 2026-04-19 15:10:02,354] A new study created in memory with name: no-name-bf0ab948-d628-464f-8e01-39c8eb683f86
[I 2026-04-19 15:10:02,357] Trial 0 finished with value: 0.014800609624694108 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.014800609624694108.
[I 2026-04-19 15:10:02,360] Trial 1 finished with value: 0.01431193896270394 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,362] Trial 2 finished with value: 0.014743379063975543 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,365] Trial 3 finished with value: 0.014795464485372594 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,369] Trial 4 finished with value: 0.014800692849330587 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,371] Trial 5 finished with value: 0.014800692850002845 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,374] Trial 6 finished with value: 0.014800694113554181 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,376] Trial 7 finished with value: 0.014427598214390287 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,379] Trial 8 finished with value: 0.014795223891564808 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,382] Trial 9 finished with value: 0.014762913625318178 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,386] Trial 10 finished with value: 0.014336742055028667 and parameters: {'alpha': 6854.231317270694}. Best is trial 1 with value: 0.01431193896270394.
[I 2026-04-19 15:10:02,390] Trial 11 finished with value: 0.014307608702673164 and parameters: {'alpha': 2903.3273118298125}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,394] Trial 12 finished with value: 0.014336306537989132 and parameters: {'alpha': 6799.817639995918}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,398] Trial 13 finished with value: 0.014562721832219962 and parameters: {'alpha': 391.4540216795501}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,403] Trial 14 finished with value: 0.014800553105994431 and parameters: {'alpha': 0.16530252489634306}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,407] Trial 15 finished with value: 0.014447310931532701 and parameters: {'alpha': 758.0062361536859}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,410] Trial 16 finished with value: 0.014340695400207963 and parameters: {'alpha': 7368.930627344862}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,414] Trial 17 finished with value: 0.01479948414144087 and parameters: {'alpha': 1.4179467109055053}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,418] Trial 18 finished with value: 0.014729564555684176 and parameters: {'alpha': 90.63317529974563}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,422] Trial 19 finished with value: 0.01449369918689413 and parameters: {'alpha': 583.4815735673367}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,426] Trial 20 finished with value: 0.014800612844303538 and parameters: {'alpha': 0.09538866305948149}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,430] Trial 21 finished with value: 0.014331179798703651 and parameters: {'alpha': 6186.9271817337985}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,434] Trial 22 finished with value: 0.014329226293358813 and parameters: {'alpha': 1784.3220682786118}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,439] Trial 23 finished with value: 0.014355188952697474 and parameters: {'alpha': 1384.7044414048485}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,442] Trial 24 finished with value: 0.014679917588826957 and parameters: {'alpha': 164.4589404079545}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,530] Trial 25 finished with value: 0.014786008587395906 and parameters: {'alpha': 17.473703000695416}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,538] Trial 26 finished with value: 0.014322061414690845 and parameters: {'alpha': 1962.0617048895194}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,548] Trial 27 finished with value: 0.014313803912597645 and parameters: {'alpha': 2273.9588728017634}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,555] Trial 28 finished with value: 0.014627446252128964 and parameters: {'alpha': 255.05453260270428}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,560] Trial 29 finished with value: 0.014800407029243678 and parameters: {'alpha': 0.33630107272992804}. Best is trial 11 with value: 0.014307608702673164.
[I 2026-04-19 15:10:02,563] A new study created in memory with name: no-name-582d8b4b-cb07-42b3-b5cc-a8ef0d47a747
[I 2026-04-19 15:10:02,567] Trial 0 finished with value: 0.014570619293123982 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.014570619293123982.
[I 2026-04-19 15:10:02,569] Trial 1 finished with value: 0.014212832875418822 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,572] Trial 2 finished with value: 0.014528650393027753 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,574] Trial 3 finished with value: 0.014566849557569051 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,577] Trial 4 finished with value: 0.014570680264634681 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,579] Trial 5 finished with value: 0.014570680265127187 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,582] Trial 6 finished with value: 0.014570681190820903 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,585] Trial 7 finished with value: 0.014295781171969666 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,587] Trial 8 finished with value: 0.014566673263354805 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,590] Trial 9 finished with value: 0.014542984887546401 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,594] Trial 10 finished with value: 0.014231815434985627 and parameters: {'alpha': 6854.231317270694}. Best is trial 1 with value: 0.014212832875418822.
[I 2026-04-19 15:10:02,598] Trial 11 finished with value: 0.014208693205265977 and parameters: {'alpha': 2903.3273118298125}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,602] Trial 12 finished with value: 0.014231499757625693 and parameters: {'alpha': 6799.817639995918}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,606] Trial 13 finished with value: 0.014395644934003991 and parameters: {'alpha': 391.4540216795501}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,609] Trial 14 finished with value: 0.014570577886650444 and parameters: {'alpha': 0.16530252489634306}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,614] Trial 15 finished with value: 0.014310351949320198 and parameters: {'alpha': 758.0062361536859}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,617] Trial 16 finished with value: 0.014234651624773725 and parameters: {'alpha': 7368.930627344862}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,621] Trial 17 finished with value: 0.014569794731665505 and parameters: {'alpha': 1.4179467109055053}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,625] Trial 18 finished with value: 0.01451850752668578 and parameters: {'alpha': 90.63317529974563}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,629] Trial 19 finished with value: 0.01434464921231902 and parameters: {'alpha': 583.4815735673367}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,633] Trial 20 finished with value: 0.014570621651857246 and parameters: {'alpha': 0.09538866305948149}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,637] Trial 21 finished with value: 0.014227738371689037 and parameters: {'alpha': 6186.9271817337985}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,640] Trial 22 finished with value: 0.014223547587390539 and parameters: {'alpha': 1784.3220682786118}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,644] Trial 23 finished with value: 0.014242432096474916 and parameters: {'alpha': 1384.7044414048485}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,648] Trial 24 finished with value: 0.014482016678755373 and parameters: {'alpha': 164.4589404079545}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,652] Trial 25 finished with value: 0.014559919694810243 and parameters: {'alpha': 17.473703000695416}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,656] Trial 26 finished with value: 0.014218417748774637 and parameters: {'alpha': 1962.0617048895194}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,660] Trial 27 finished with value: 0.014212628281497781 and parameters: {'alpha': 2273.9588728017634}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,664] Trial 28 finished with value: 0.014443384664435257 and parameters: {'alpha': 255.05453260270428}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,668] Trial 29 finished with value: 0.014570470868194085 and parameters: {'alpha': 0.33630107272992804}. Best is trial 11 with value: 0.014208693205265977.
[I 2026-04-19 15:10:02,671] A new study created in memory with name: no-name-d9db6364-a01b-451c-b0a2-f6d694d4923a
[I 2026-04-19 15:10:02,674] Trial 0 finished with value: 0.014834841204363469 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.014834841204363469.
[I 2026-04-19 15:10:02,676] Trial 1 finished with value: 0.014266787125256874 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,679] Trial 2 finished with value: 0.014778987715300416 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,682] Trial 3 finished with value: 0.014829866502819465 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,684] Trial 4 finished with value: 0.014834921599171597 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,687] Trial 5 finished with value: 0.014834921599820984 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,690] Trial 6 finished with value: 0.014834922820390848 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,693] Trial 7 finished with value: 0.014441667960821558 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,695] Trial 8 finished with value: 0.014829633660984082 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,698] Trial 9 finished with value: 0.014798183178140063 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,702] Trial 10 finished with value: 0.014283185787979281 and parameters: {'alpha': 6854.231317270694}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,706] Trial 11 finished with value: 0.014272159876222152 and parameters: {'alpha': 2903.3273118298125}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,710] Trial 12 finished with value: 0.014282823568670807 and parameters: {'alpha': 6799.817639995918}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,714] Trial 13 finished with value: 0.014593687412372588 and parameters: {'alpha': 391.4540216795501}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,718] Trial 14 finished with value: 0.014834786606109554 and parameters: {'alpha': 0.16530252489634306}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,722] Trial 15 finished with value: 0.014464938387697138 and parameters: {'alpha': 758.0062361536859}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,725] Trial 16 finished with value: 0.014286525266762365 and parameters: {'alpha': 7368.930627344862}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,729] Trial 17 finished with value: 0.014833753762687698 and parameters: {'alpha': 1.4179467109055053}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,733] Trial 18 finished with value: 0.014765326999607333 and parameters: {'alpha': 90.63317529974563}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,737] Trial 19 finished with value: 0.014518024865634452 and parameters: {'alpha': 583.4815735673367}. Best is trial 1 with value: 0.014266787125256874.
[I 2026-04-19 15:10:02,741] Trial 20 finished with value: 0.014834844314541833 and parameters: {'alpha': 0.09538866305948149}. Best is trial 1 with value: 0.014266787125256874.

In [59]:
results_pca_ridge = pd.DataFrame({
    "h=1":  res_pca_ridge_1,
    "h=5":  res_pca_ridge_5,
    "h=20": res_pca_ridge_20,
}).T
display(results_pca_ridge.drop(columns=["pca_explained_variance_folds"], errors="ignore").round(6))

,mean_oos_ic,tstat_ic,mean_oos_rmse,mean_oos_r2,mean_oos_pca_explained_variance
h=1,0.015835,0.766141,0.014567,-0.016966,0.706731
h=5,0.287368,10.220156,0.029731,0.003106,0.735228
h=20,0.425698,7.838713,0.050276,-0.200333,0.757687

PLS

In [61]:
from sklearn.cross_decomposition import PLSRegression
def pls_oos_table(splits, n_components_list):
    rows = []

    for n_components in n_components_list:
        ev_folds = []

        for fold in splits:
            X_train = fold["X_train"]
            Y_train = fold["Y_train"].values.ravel()
            X_test  = fold["X_test"]

            scaler = StandardScaler()
            X_train_s = scaler.fit_transform(X_train)
            X_test_s  = scaler.transform(X_test)

            pls = PLSRegression(n_components=n_components)
            pls.fit(X_train_s, Y_train)

            T_test = pls.transform(X_test_s)
            X_test_hat = T_test @ pls.x_loadings_.T

            ss_total = np.sum(X_test_s ** 2)
            ss_resid = np.sum((X_test_s - X_test_hat) ** 2)

            ev_folds.append(1 - ss_resid / ss_total)

        rows.append({
            "n_components": n_components,
            "mean_oos_explained_variance": np.mean(ev_folds),
        })

    return pd.DataFrame(rows)

In [62]:
tab_pls_1 = pls_oos_table(splits1, [1, 2, 3, 5, 10, 15, 20])
tab_pls_5 = pls_oos_table(splits5, [1, 2, 3, 5, 10, 15, 20])
tab_pls_20 = pls_oos_table(splits20, [1, 2, 3, 5, 10, 15, 20])

display(tab_pls_1.round(4))
display(tab_pls_5.round(4))
display(tab_pls_20.round(4))

   n_components  mean_oos_explained_variance
0             1                       0.2126
1             2                       0.3372
2             3                       0.4123
3             5                       0.5162
4            10                       0.6793
5            15                       0.7998
6            20                       0.8885

   n_components  mean_oos_explained_variance
0             1                       0.2801
1             2                       0.3983
2             3                       0.4709
3             5                       0.5510
4            10                       0.7083
5            15                       0.8429
6            20                       0.9654

   n_components  mean_oos_explained_variance
0             1                       0.2729
1             2                       0.4096
2             3                       0.4929
3             5                       0.5856
4            10                       0.7702
5            15                       0.9159
6            20                       0.9840

In [63]:
res_pls_1  = pls_oos(splits1,  n_components=10)
res_pls_5  = pls_oos(splits5,  n_components=10)
res_pls_20 = pls_oos(splits20, n_components=10)

In [64]:
results_pls = pd.DataFrame({
    "h=1":  res_pls_1,
    "h=5":  res_pls_5,
    "h=20": res_pls_20,
}).T

display(results_pls.round(6))

      mean_oos_ic   tstat_ic  mean_oos_rmse  mean_oos_r2
h=1      0.011292   0.592072       0.014992    -0.102011
h=5      0.313119  11.156461       0.029899    -0.028231
h=20     0.404086   6.928618       0.052514    -0.320116

MLP autoencoder

In [68]:
from sklearn.neural_network import MLPRegressor

def ae_oos_table(splits, latent_dims):
    rows = []

    for k in latent_dims:
        ev_folds = []

        for f in splits:
            X_tr = f["X_train"]
            X_te = f["X_test"]

            sc = StandardScaler()
            X_tr_s = sc.fit_transform(X_tr)
            X_te_s = sc.transform(X_te)
            ae = MLPRegressor(
    hidden_layer_sizes=(50, k, 50),
    activation="relu",
    max_iter=200,
    random_state=42
)
            ae.fit(X_tr_s, X_tr_s)
            X_hat = ae.predict(X_te_s)

            ss_total = np.sum(X_te_s ** 2)
            ss_resid = np.sum((X_te_s - X_hat) ** 2)

            ev_folds.append(1 - ss_resid / ss_total)

        rows.append({
            "latent_dim": k,
            "mean_oos_explained_variance": np.mean(ev_folds),
        })

    return pd.DataFrame(rows)

In [69]:
tab_ae_1  = ae_oos_table(splits1,  [2, 5, 10, 20])
tab_ae_5  = ae_oos_table(splits5,  [2, 5, 10, 20])
tab_ae_20 = ae_oos_table(splits20, [2, 5, 10, 20])

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [70]:
display(tab_ae_1.round(4))
display(tab_ae_5.round(4))
display(tab_ae_20.round(4))

   latent_dim  mean_oos_explained_variance
0           2                       0.3856
1           5                       0.5698
2          10                       0.8049
3          20                       0.9761

   latent_dim  mean_oos_explained_variance
0           2                       0.4387
1           5                       0.6020
2          10                       0.8477
3          20                       0.9832

   latent_dim  mean_oos_explained_variance
0           2                       0.4236
1           5                       0.6019
2          10                       0.8342
3          20                       0.9787

In [71]:
def ae_ridge_oos(splits, k=10, val_size=252, n_trials=30, seed=42):
    y_true_folds = []
    y_pred_folds = []

    for f in splits:
        X_train = f["X_train"]
        Y_train = f["Y_train"].values.ravel()
        X_test  = f["X_test"]
        Y_test  = f["Y_test"].values.ravel()

        X_tr  = X_train.iloc[:-val_size]
        y_tr  = Y_train[:-val_size]
        X_val = X_train.iloc[-val_size:]
        y_val = Y_train[-val_size:]

        def relu(x):
            return np.maximum(0, x)

        def encode_middle(ae, X):
            H1 = relu(X @ ae.coefs_[0] + ae.intercepts_[0])
            Z  = relu(H1 @ ae.coefs_[1] + ae.intercepts_[1])   
            return Z

        def objective(trial):
            alpha = trial.suggest_float("alpha", 1e-4, 1e4, log=True)

            sc = StandardScaler()
            X_tr_s  = sc.fit_transform(X_tr)
            X_val_s = sc.transform(X_val)

            ae = MLPRegressor(
                hidden_layer_sizes=(50, k, 50),
                activation="relu",
                max_iter=200,
                random_state=seed
            )
            ae.fit(X_tr_s, X_tr_s)

            Z_tr  = encode_middle(ae, X_tr_s)
            Z_val = encode_middle(ae, X_val_s)

            model = Ridge(alpha=alpha)
            model.fit(Z_tr, y_tr)
            y_val_pred = model.predict(Z_val)

            return rmse(y_val, y_val_pred)

        study = optuna.create_study(
            direction="minimize",
            sampler=optuna.samplers.TPESampler(seed=seed)
        )
        study.optimize(objective, n_trials=n_trials, show_progress_bar=False)
        best_alpha = study.best_params["alpha"]

        sc = StandardScaler()
        X_train_s = sc.fit_transform(X_train)
        X_test_s  = sc.transform(X_test)

        ae = MLPRegressor(
            hidden_layer_sizes=(50, k, 50),
            activation="relu",
            max_iter=200,
            random_state=seed
        )
        ae.fit(X_train_s, X_train_s)

        Z_train = encode_middle(ae, X_train_s)
        Z_test  = encode_middle(ae, X_test_s)

        model = Ridge(alpha=best_alpha)
        model.fit(Z_train, Y_train)
        y_pred = model.predict(Z_test)

        y_true_folds.append(Y_test)
        y_pred_folds.append(y_pred)

    return oos_metrics(y_true_folds, y_pred_folds)

In [72]:
res_ae_ridge_1  = ae_ridge_oos(splits1,  k=10, val_size=252, n_trials=30)
res_ae_ridge_5  = ae_ridge_oos(splits5,  k=10, val_size=252, n_trials=30)
res_ae_ridge_20 = ae_ridge_oos(splits20, k=10, val_size=252, n_trials=30)

[I 2026-04-19 15:48:15,842] A new study created in memory with name: no-name-4c719640-f592-440a-8a1e-dc265afb249f
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:16,450] Trial 0 finished with value: 0.014668791876674584 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.014668791876674584.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:17,032] Trial 1 finished with value: 0.014232399593830766 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:17,592] Trial 2 finished with value: 0.014606625210145167 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:18,169] Trial 3 finished with value: 0.014662977568652985 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:18,848] Trial 4 finished with value: 0.01466888630552285 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:19,414] Trial 5 finished with value: 0.014668886306285659 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:19,993] Trial 6 finished with value: 0.014668887740037636 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:20,580] Trial 7 finished with value: 0.01434107435620278 and parameters: {'alpha': 849.9808989183019}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:21,148] Trial 8 finished with value: 0.014662706811498309 and parameters: {'alpha': 6.440507553993717}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:21,715] Trial 9 finished with value: 0.014627238587997084 and parameters: {'alpha': 46.19347374377382}. Best is trial 1 with value: 0.014232399593830766.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:22,305] Trial 10 finished with value: 0.0142194633522547 and parameters: {'alpha': 6854.231317270694}. Best is trial 10 with value: 0.0142194633522547.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:22,916] Trial 11 finished with value: 0.014244233315502052 and parameters: {'alpha': 2903.3273118298125}. Best is trial 10 with value: 0.0142194633522547.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:23,487] Trial 12 finished with value: 0.014223300297527752 and parameters: {'alpha': 5705.54173238389}. Best is trial 10 with value: 0.0142194633522547.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:24,083] Trial 13 finished with value: 0.014487720320863807 and parameters: {'alpha': 272.72982185916777}. Best is trial 10 with value: 0.0142194633522547.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:24,676] Trial 14 finished with value: 0.014215735904825114 and parameters: {'alpha': 8467.975927999696}. Best is trial 14 with value: 0.014215735904825114.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:25,290] Trial 15 finished with value: 0.014668833373882919 and parameters: {'alpha': 0.05635602497291169}. Best is trial 14 with value: 0.014215735904825114.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:25,858] Trial 16 finished with value: 0.01446234890615289 and parameters: {'alpha': 333.65932463125364}. Best is trial 14 with value: 0.014215735904825114.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:26,419] Trial 17 finished with value: 0.014666858073896135 and parameters: {'alpha': 2.1003179206161295}. Best is trial 14 with value: 0.014215735904825114.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:27,016] Trial 18 finished with value: 0.014605816606846267 and parameters: {'alpha': 72.81630248279436}. Best is trial 14 with value: 0.014215735904825114.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:27,575] Trial 19 finished with value: 0.014213877998246815 and parameters: {'alpha': 9590.683921983196}. Best is trial 19 with value: 0.014213877998246815.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:28,158] Trial 20 finished with value: 0.014668545847679008 and parameters: {'alpha': 0.3530343009318503}. Best is trial 19 with value: 0.014213877998246815.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:28,750] Trial 21 finished with value: 0.014220851391456417 and parameters: {'alpha': 6393.140913511499}. Best is trial 19 with value: 0.014213877998246815.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:29,333] Trial 22 finished with value: 0.014342909665126023 and parameters: {'alpha': 836.8671967096351}. Best is trial 19 with value: 0.014213877998246815.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:29,937] Trial 23 finished with value: 0.01421545232013186 and parameters: {'alpha': 8621.496643688846}. Best is trial 19 with value: 0.014213877998246815.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:30,504] Trial 24 finished with value: 0.014300199567495751 and parameters: {'alpha': 1248.311507322139}. Best is trial 19 with value: 0.014213877998246815.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:31,088] Trial 25 finished with value: 0.014526592195024005 and parameters: {'alpha': 194.3560960129936}. Best is trial 19 with value: 0.014213877998246815.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:31,654] Trial 26 finished with value: 0.014655123964793789 and parameters: {'alpha': 14.528624920816956}. Best is trial 19 with value: 0.014213877998246815.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:32,235] Trial 27 finished with value: 0.01421350527281415 and parameters: {'alpha': 9855.415049127516}. Best is trial 27 with value: 0.01421350527281415.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:32,827] Trial 28 finished with value: 0.014291792054583821 and parameters: {'alpha': 1369.4130987707636}. Best is trial 27 with value: 0.01421350527281415.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:33,395] Trial 29 finished with value: 0.01466876574562425 and parameters: {'alpha': 0.12611119254047898}. Best is trial 27 with value: 0.01421350527281415.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:34,049] A new study created in memory with name: no-name-30055e65-1aa0-44f4-828f-d3cccd618d53
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:34,652] Trial 0 finished with value: 0.018451687400799045 and parameters: {'alpha': 0.09915644566638405}. Best is trial 0 with value: 0.018451687400799045.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:35,286] Trial 1 finished with value: 0.01602996359726662 and parameters: {'alpha': 4033.800832600386}. Best is trial 1 with value: 0.01602996359726662.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:35,909] Trial 2 finished with value: 0.017486714222127758 and parameters: {'alpha': 71.77141927992028}. Best is trial 1 with value: 0.01602996359726662.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:36,511] Trial 3 finished with value: 0.018354926599933045 and parameters: {'alpha': 6.155564318973023}. Best is trial 1 with value: 0.01602996359726662.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:37,162] Trial 4 finished with value: 0.0184532692859248 and parameters: {'alpha': 0.001770716864353783}. Best is trial 1 with value: 0.01602996359726662.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:37,779] Trial 5 finished with value: 0.018453269298704812 and parameters: {'alpha': 0.001769930294063334}. Best is trial 1 with value: 0.01602996359726662.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:38,427] Trial 6 finished with value: 0.01845329331966672 and parameters: {'alpha': 0.00029152036385288323}. Best is trial 1 with value: 0.01602996359726662.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:39,045] Trial 7 finished with value: 0.015687284695706273 and parameters: {'alpha': 849.9808989183019}. Best is trial 7 with value: 0.015687284695706273.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:39,694] Trial 8 finished with value: 0.018350451646184027 and parameters: {'alpha': 6.440507553993717}. Best is trial 7 with value: 0.015687284695706273.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:40,284] Trial 9 finished with value: 0.01778906293320778 and parameters: {'alpha': 46.19347374377382}. Best is trial 7 with value: 0.015687284695706273.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:40,935] Trial 10 finished with value: 0.015767972279485738 and parameters: {'alpha': 6772.683723165199}. Best is trial 7 with value: 0.015687284695706273.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:41,583] Trial 11 finished with value: 0.016080969845610766 and parameters: {'alpha': 2848.9649355580086}. Best is trial 7 with value: 0.015687284695706273.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
[I 2026-04-19 15:48:42,234] Trial 12 finished with value: 0.015874663580847118 and parameters: {'alpha': 5705.54173238389}. Best is trial 7 with value: 0.015687284695706273.
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(

In [73]:
results_ae_ridge = pd.DataFrame({
    "h=1": res_ae_ridge_1,
    "h=5": res_ae_ridge_5,
    "h=20": res_ae_ridge_20,
}).T
display(results_ae_ridge.round(6))

      mean_oos_ic  tstat_ic  mean_oos_rmse  mean_oos_r2
h=1     -0.004341 -0.226999       0.014774    -0.055886
h=5      0.284496  9.495519       0.029861    -0.008539
h=20     0.400924  6.669643       0.051017    -0.239910

comparison

In [77]:
def clean(res, drop_cols=None):
    if drop_cols is None:
        drop_cols = []
    return {k: v for k, v in res.items() if k not in drop_cols}


rows = []

for h, res_ae, res_pca, res_pls, res_ridge, res_zero in [
    (1,  res_ae_ridge_1,  res_pca_ridge_1,  res_pls_1,  res_ridge_1,  res1),
    (5,  res_ae_ridge_5,  res_pca_ridge_5,  res_pls_5,  res_ridge_5,  res5),
    (20, res_ae_ridge_20, res_pca_ridge_20, res_pls_20, res_ridge_20, res20),
]:
    rows.append({"model": "AE+Ridge", "h": h, **clean(res_ae)})
    rows.append({"model": "PCA+Ridge", "h": h, **clean(res_pca, ["pca_explained_variance_folds"])})
    rows.append({"model": "PLS", "h": h, **clean(res_pls)})
    rows.append({"model": "Ridge", "h": h, **clean(res_ridge)})
    rows.append({"model": "Zero", "h": h, **clean(res_zero)})

comparison = pd.DataFrame(rows)
comparison = comparison.set_index(["model", "h"]).sort_index()

display(comparison.round(6))

              mean_oos_ic   tstat_ic  mean_oos_rmse  mean_oos_r2  \
model     h
AE+Ridge  1     -0.004341  -0.226999       0.014774    -0.055886
          5      0.284496   9.495519       0.029861    -0.008539
          20     0.400924   6.669643       0.051017    -0.239910
PCA+Ridge 1      0.015835   0.766141       0.014567    -0.016966
          5      0.287368  10.220156       0.029731     0.003106
          20     0.425698   7.838713       0.050276    -0.200333
PLS       1      0.011292   0.592072       0.014992    -0.102011
          5      0.313119  11.156461       0.029899    -0.028231
          20     0.404086   6.928618       0.052514    -0.320116
Ridge     1      0.025696   1.346186       0.014576    -0.018322
          5      0.308879  11.031029       0.030568    -0.090637
          20     0.421551   7.587647       0.050423    -0.208463
Zero      1           NaN        NaN       0.014553    -0.014521
          5           NaN        NaN       0.031467    -0.096768
          20          NaN        NaN       0.058803    -0.614936

              mean_oos_pca_explained_variance
model     h
AE+Ridge  1                               NaN
          5                               NaN
          20                              NaN
PCA+Ridge 1                          0.706731
          5                          0.735228
          20                         0.757687
PLS       1                               NaN
          5                               NaN
          20                              NaN
Ridge     1                               NaN
          5                               NaN
          20                              NaN
Zero      1                               NaN
          5                               NaN
          20                              NaN